### ISSUE TITLE
Hardware connections

### ISSUE THREAD

**Issue by Zhoev1405** [voelkerb/STPM3X#1] opened 2021-08-14 11:51 UTC
Hi,

I want to do SPI communication between ESP32 board and Eval-STPM34 metrology board , i am trying to read just a register of the Eval-STPM34 but i always fail , i used these pins to ensure the SPI communication :

 

ESP32 -----> EVAL-STPM34

GPIO 23 MOSI-----> MOSI  

GPIO 19 MISO-----> MISO

GPIO 18 SCL -----> SCL

GPIO 5 SCS -----> SCS

GPIO 14 -----> SYN

GPIO 12  -----> RES

GND -----> GND

VCC -----> VCC

![Untitled](https://user-images.githubusercontent.com/88930917/129447023-3bc31fe1-8115-465b-b3bb-4e207265e128.png)

 where am i doing the mistake?

how can i do both on video  https://www.youtube.com/watch?v=1S5WECN2qnI with your library

**Comment by voelkerb** [comment] 2021-08-23 09:43
Hey @Zhoev1405 

Your connection seems about right.
Can you double check that:
- with "RES" you refer to the EN Pin of the STPM3X
- the SPI connection: MISO -> IO19, MOSI -> IO23, SCK -> IO18
- CS -> IO5, SYN -> IO14, RES -> IO12 
Your screenshot shows that you use other pins for CS, SYN and RES. While this should be totally fine, I just want to exclude possible invalid pin configurations. 

Does stpm3x.init() return false, meaning that initialization has failed?
I double checked that with my stpm34 eval board and I can report that the code seems to work just fine. 

Have you set all Jumpers to SPI and supplied the eval board with power?
You should also disconnect J4 completely.

**Comment by Zhoev1405** [comment] 2021-09-01 13:24
how can i use uart instead of spi?

**Comment by voelkerb** [comment] 2021-09-09 12:04
Hey @Zhoev1405,

The library only supports SPI connection. I think ST offers a dedicated application for testing the eval board via the RS232 link.

BR
Ben

**Comment by Zhoev1405** [comment] 2021-10-23 12:32
> Hey @Zhoev1405,
> 
> The library only supports SPI connection. I think ST offers a dedicated application for testing the eval board via the RS232 link.
> 
> BR Ben

I connected on ESP32 and everything works well but it would be good if there was  a great guide to registers I get volts and active power but how to get the network frequency? and how to calibrate?

**Comment by Zhoev1405** [comment] 2021-10-23 18:19
please tell me where to connect stpm vcc esp32 v3.3 or v5? when I connect to 5v everything works correctly and when v3.3 then stpm does not work correctly

**Comment by voelkerb** [comment] 2024-04-03 06:07
My demo board uses 5V also. I am unsure as the data sheet states 3.3V should be sufficient. If you have more insides now, please advise.

**Comment by aaltonen1024** [comment] 2024-07-25 09:25
Hi,
I've been trying to setup a communication between ESP32 and STPM32 evaluation board. This is how I do the wiring between them :
ESP32 -----> EVAL-STPM32
GPIO 23 -----> MOSI
GPIO 19 -----> MISO
GPIO 18  -----> SCL
GPIO 5 -----> SCS
GPIO 14 -----> SYN
GND -----> GND
VCC -----> VCC

you said to disconnect J4 completely. Does that mean I should remove the jumper, and connect GPIO 12 to 'En' pin ? I also put my VCC to 5V on ESP32, but I got this numbers every time ( I haven't connect the sensor to a power source yet ). Is this an expected behavior? 

![image](https://github.com/user-attachments/assets/93f42ff4-3011-4f54-b1aa-a56878923766)

**Comment by voelkerb** [comment] 2024-07-25 11:31
@aaltonen1024 Yes, exactly. Remove the jumper and connect the `En` pin, which is the 4th pin on `J5` to whatever you defined as the `RES` pin. Make sure you supply power to the board on `J5` (`VCC`, `GND`) as well.
The inputs should **wiggle** a little bit. Fixed values like you get indicate that sth. is not correctly wired. You can also hook up an oscilloscope/LA and see if the chip responds.

**Comment by aaltonen1024** [comment] 2024-08-01 08:17
I still can't get it right even after removing the jumper on `J4` and connect the `En` pin to `RES` pin. I must be getting something wrong. Just to clarify, 

Here's how I assume how the `J6` pins are positioned by seeing the little number '1' on the top right corner
![diagram](https://github.com/user-attachments/assets/4169c0ff-5d7a-4768-b689-055effdeb54b)
![J5](https://github.com/user-attachments/assets/b2e3051d-48d1-41c0-a516-255abb31e5f2)


and here's the pin list from the datasheet
![J5 PINS](https://github.com/user-attachments/assets/e2db348b-a632-4eb3-bc24-30f46518df19)

and I assume the same layout is also used for `J5` digital pins?

**Comment by voelkerb** [comment] 2024-08-01 08:36
I used the eval board schematics below for all my testing. This shows the layout and numbering of the header. The position of pin 1 is marked on the eval board. 

![image](https://github.com/user-attachments/assets/10adaacd-5ca9-41ac-98ce-6fbaf95e693a)

Can you hook up a logic analyser or oscilloscope to the SPI lines to see if you get an answer on the MISO line?

Other things to look out for:
* Chip VCC same as uC VCC
* Common GND
* SCS LOW when SCL shows clocks
* Check for broken wires

Unfortunately I don't have an eval board at hand ATM. Wiring should however be in line with this [schematic (page 2 + 3)](https://github.com/voelkerb/powermeter/blob/master/Schematic/Version_2/powermeterV2.pdf).

**Comment by aaltonen1024** [comment] 2024-08-06 08:12
I got it to work now, it's gotta be faulty wires because I replaced them all. Thank you for your help

**Comment by voelkerb** [comment] 2024-08-06 08:45
You're welcome. I think I will close the issue.

**Closed as completed** 2024-08-06 08:45 UTC
